sudo: false
language: java

cache:
  directories:
    - $HOME/.gradle

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

# Sadly, install-jdk.sh seems to be broken with GraalVM on MacOS, so we install it manually.

jobs:
  include:
    # Linux + OpenJDK 11
    - os: linux
      env:
       - JDK='Open JDK 11'
       - JAVA_HOME=$HOME/jdk
      install:
       - source ./install-jdk.sh --feature 11 --target $JAVA_HOME
       - export PATH="$JAVA_HOME/bin:$PATH"
    # Linux + GraalVM 20.1.0 @ Java 8
    - os: linux
      env:
       - JDK='GraalVM 20.1.0 @ Java 8'
       - JAVA_HOME=$HOME/jdk
      install:
       - source ./install-jdk.sh --target $JAVA_HOME --url "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.1.0/graalvm-ce-java8-linux-amd64-20.1.0.tar.gz"
       - export PATH="$JAVA_HOME/bin:$PATH"
       - gu install native-image
    # Linux + GraalVM 20.1.0 @ Java 11
    - os: linux
      env:
       - JDK='GraalVM 20.1.0 @ Java 11'
       - JAVA_HOME=$HOME/jdk
      install:
       - source ./install-jdk.sh --target $JAVA_HOME --url "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.1.0/graalvm-ce-java11-linux-amd64-20.1.0.tar.gz"
       - export PATH="$JAVA_HOME/bin:$PATH"
       - gu install native-image
    # MacOS + OpenJDK 11
    - os: osx
      env:
       - JDK='Open JDK 11'
       - JAVA_HOME=$HOME/jdk
      install:
       - source ./install-jdk.sh --feature 11 --target $JAVA_HOME
       - export PATH="$JAVA_HOME/bin:$PATH"
    # MacOS + GraalVM 20.1.0 @ Java 8
    - os: osx
      env:
       - JDK='GraalVM 20.1.0 @ Java 8'
       - JAVA_HOME=$HOME/jdk/Contents/Home
      install:
       - wget https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.1.0/graalvm-ce-java8-darwin-amd64-20.1.0.tar.gz
       - gunzip -c graalvm-ce-java8-darwin-amd64-20.1.0.tar.gz | tar xopf -
       - mv graalvm-ce-java8-20.1.0 $HOME/jdk
       - export PATH="$JAVA_HOME/bin:$PATH"
       - gu install native-image
    # MacOS + GraalVM 20.1.0 @ Java 11
    - os: osx
      env:
       - JDK='GraalVM 20.1.0 @ Java 11'
       - JAVA_HOME=$HOME/jdk/Contents/Home
      install:
       - wget "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.1.0/graalvm-ce-java11-darwin-amd64-20.1.0.tar.gz"
       - gunzip -c graalvm-ce-java11-darwin-amd64-20.1.0.tar.gz | tar xopf -
       - mv graalvm-ce-java11-20.1.0 $HOME/jdk
       - export PATH="$JAVA_HOME/bin:$PATH"
       - gu install native-image

script:
  - echo $JAVA_HOME
  - java -Xmx32m -version
  - ./gradlew --no-daemon check